### ISSUE TITLE
Adding multiple NICs using resource ddcloud_server vs. ddcloud_server_nic

### ISSUE THREAD

**Issue by wninobla** [DimensionDataResearch/terraform-provider-ddcloud#39]
What is the preferred method of getting this done?  The new resource will add the NIC but requires a restart of the target VM which isn't so much a big deal.  But, a customer may want to try to include the multi-NIC definition in the resource ddcloud_server.  I didn't happen to see it in the documentation so not sure if that's an option.  Thoughts?

**Comment by tintoy** [comment]
Unfortunately this isn't really practical - consider it a mismatch between how Terraform works and limitations of the CloudControl API. I can explain further if you're interested but the key point here is that we can't reliably identify the various individual NICs if they appear _under_ the ddcloud_server resource (because all NIC properties are mutable).

If we treated them as separate resources but still allowed them to appear inside the ddcloud_server then it would look awkward because each ddcloud_server_nic would need to still specify the target server Id as one of its properties.

**Comment by tintoy** [comment]
Ah - do you mean creating the server with all the NICs already present from the start? Could be tricky.

But we might be able to move the additional NIC resources under the server if we add an arbitrary "index" property to each NIC.

**Comment by wninobla** [comment]
Yes - from the start.  I can live with the other method of adding after the fact.  However, if we're going about spinning up infrastructure as a final configuration from the get go it would stand to reason we'd be able to specify this in the ddcloud_server resource all at once as ollosed to relying on the other method that will add that as an infrastructure change/upgrade.


Regards,

William Ninobla
Sr. Solutions Architect
Cloud Business Unit
Dimension Data
________________________________

**Comment by tintoy** [comment]
Actually that might not be a meaningful distinction in the Terraform model. Will explain when I get behind a real keyboard :)

**Comment by tintoy** [comment]
Ok, so here's the thing. A server and its various NICs are part of the same configuration (in Terraform terms) because they appear across one or more files in the same folder (or module). So from that perspective at least it doesn't make a difference whether they are under a single resource (the `ddcloud_server`) or appear as separate related resources. They'll have to be created separately and managed separately _by Terraform_ although the overall operation still appears as a single `terraform apply`.

**Comment by tintoy** [comment]
@wninobla

CC: @kumarappanc @johnamurray @alexbacchin 

Now we could maybe make additional NICs behave more like disks (by giving each adapter an arbitrary `index` property) but, like disks, internally we'd still have to manage each one individually.

This is a little fragile however, because we'd need to ensure that the adapter order is maintained by CloudControl and that the index values being used remain contiguous. It's possible to do this, I think, but I'm a little concerned that the behaviour may become unintuitive for our users (could be hard for them to both form the corresponding mental model for this and then keep it in their heads while working).

For example, if I have a server with the following configuration:

``` hcl
resource "ddcloud_server" "my_server" {
  # Adapter1
  nic {
    index = 1
    private_ipv4 = "192.168.11.20"
  }

  # Adapter2
  nic {
    index = 2
    private_ipv4 = "192.168.12.20"
  }

  # Adapter3
  nic {
    index = 3
    private_ipv4 = "192.168.13.20"
  }

  # Adapter4
  nic {
    index = 4
    private_ipv4 = "192.168.14.20"
  }
}
```

Which results in the following adapters in CloudControl (think of this as an array of NICs):
- `[0] = PrimaryAdapter` (Id = `9cff777a-c7b9-4cd9-9de4-537c4e979891`)
- `[1] = Adapter1` (Id = `cfe66b62-b703-4b46-987a-bf9c963cb05a`)
- `[2] = Adapter2`  (Id = `78b4e7a2-cc4a-4f87-a073-13fd760b8027`)
- `[3] = Adapter3` (Id = `77c5bdab-544d-42cb-ac66-c1518827ff6d`)
- `[4] = Adapter4` (Id = `e6de814c-48fd-48e3-9d7e-fbf681896950`)

Now I want to delete Adapter3:

``` hcl
resource "ddcloud_server" "my_server" {
  # Adapter1
  nic {
    index = 1
    private_ipv4 = "192.168.11.20"
  }

  # Adapter2
  nic {
    index = 2
    private_ipv4 = "192.168.12.20"
  }

  # <snip!> No more Adapter3

  # Adapter4
  nic {
    index = 4
    private_ipv4 = "192.168.14.20"
  }
}
```

How is the provider supposed to match this up with what it sees in CloudControl?
- `[0] = PrimaryAdapter` (Id = `9cff777a-c7b9-4cd9-9de4-537c4e979891`)
- `[1] = Adapter1` (Id = `cfe66b62-b703-4b46-987a-bf9c963cb05a`)
- `[2] = Adapter2` (Id = `78b4e7a2-cc4a-4f87-a073-13fd760b8027`)
- `[3] = Adapter3` (Id = `77c5bdab-544d-42cb-ac66-c1518827ff6d`)
- `[4] = Adapter4` (Id = `e6de814c-48fd-48e3-9d7e-fbf681896950`)

should be:
- `[0] = PrimaryAdapter` (Id = `9cff777a-c7b9-4cd9-9de4-537c4e979891`)
- `[1] = Adapter1` (Id = `cfe66b62-b703-4b46-987a-bf9c963cb05a`)
- `[2] = Adapter2` (Id = `78b4e7a2-cc4a-4f87-a073-13fd760b8027`)
- `[3] = Adapter4` (Id = `e6de814c-48fd-48e3-9d7e-fbf681896950`)

but could _also_ be:
- `[0] = PrimaryAdapter` (Id = `9cff777a-c7b9-4cd9-9de4-537c4e979891`)
- `[1] = Adapter1` (Id = `cfe66b62-b703-4b46-987a-bf9c963cb05a`)
- `[2] = Adapter2` (Id = `78b4e7a2-cc4a-4f87-a073-13fd760b8027`)
- `[3] = Adapter3` (Id = `77c5bdab-544d-42cb-ac66-c1518827ff6d`)

So how do we tell which one has been removed (Adapter3 or Adapter4)? You might be tempted to look at their position in the list, and compare that with their index but that becomes unwieldy as soon as you have multiple adapter changes to track.

This is why we modelled NICs as separate resources, so that Terraform will track their creation / destruction separately.

FWIW, disks don't have this problem because their SCSI unit Id cannot be changed after deployment (and so it represents a unique identifier for each disk).

**Comment by tintoy** [comment]
BTW, looks like the Hashicorp devs are considering [improved support for nestable resources](https://github.com/hashicorp/terraform/issues/2275). Perhaps that would make this easier to handle?

**Comment by wninobla** [comment]
This could work maybe...  But not sure if its worth the effort.  The workaround for now as long as we know it works is fine short term.  We can follow whatever the community dictates after I suppose. =)


Regards,

William Ninobla
Sr. Solutions Architect
Cloud Business Unit
Dimension Data
________________________________

**Comment by tintoy** [comment]
Ok, I'm going to close this for now; we can reopen it if we decide to alter the implementation :)
