### ISSUE TITLE
Add the ability to manage default firewall rules

### ISSUE THREAD

**Issue by johnamurray** [DimensionDataResearch/terraform-provider-ddcloud#54]
When you standup a network domain it comes with a set of default firewall rules that currently cannot be managed by terraform as it doesn't create them. I would like to disable (in particular) the rule that denies all inbound IPv6 traffic. 

@tintoy could maybe point me in the right direction and I can try and sort out. Maybe a data resource?

**Comment by wninobla** [comment]
Hi John,

@johnamurray In terms of how Terraform works that isn't necessarily how you would typically go about disabling a resource that wasn't originally spun up by Terraform.  You could I suppose export the configuration to get it to be recognized by the terraforn state file but this is something better server via an API call or a post transaction via Ansible or Chef.

**Comment by tintoy** [comment]
I'm thinking maybe they might work better as settings on the network domain (data sources are read-only, BTW).

Something like:

```hcl
resource "ddcloud_networkdomain" "my_domain" {
  name = "My Domain"

  default_firewall_rule {
    type = "BlockOutboundMailIPv4"
    enabled = true
  }

  default_firewall_rule {
    type = "DenyExternalInboundIPv6"
    enabled = false
  }
}
```

Note that the `CCDEFAULT.` prefix is not included in the rule type. This makes it harder to anyone to think they can control a regular firewall rule with this.

CC: @johnamurray @alexbacchin 

PS. @wninobla ordinarily I'd agree with you here, but I think this might be a special case; without the ability to manage the enablement of these rules, a large proportion of the the use cases for this provider would be unnecessarily difficult to achieve. I think if we tie them to the network domain then Terraform's life-cycle model won't be violated.

**Comment by johnamurray** [comment]
@wninobla - true but the reason I want to get the IPV6 deny disabled is so that a server can bootstrap using chef (or whatever) on ipv6 rather than giving it a public ipv4 address. My hack at the moment is a null resource that does an api call to disable the rule

**Comment by tintoy** [comment]
Implemented in [v1.1.7](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/releases/tag/v1.1.7).

**Comment by wninobla** [comment]
OK that makes more sense to me.  We don't get a load of people trying to use IPv6 in that sense since they are rather slow in the transition from traditional IPv4 address space.  Sounds to me between you and Adam we will want to get in a feature enhancement to the build.


________________________________

**Comment by tintoy** [comment]
(cough) This has already been implemented :)

On 29 Nov 2016, at 3:19 AM, wninobla 

OK that makes more sense to me. We don't get a load of people trying to use IPv6 in that sense since they are rather slow in the transition from traditional IPv4 address space. Sounds to me between you and Adam we will want to get in a feature enhancement to the build.
