### ISSUE TITLE
Deploying Multiple Network Domains

### ISSUE THREAD

**Issue by mingsheng36** [DimensionDataResearch/terraform-provider-ddcloud#57]
Whenever I try to deploy 2 or more network domains, only one will be successfully created. The second one will always face 400 unexpected error.

**Comment by tintoy** [comment]
Hi :)

Yes, this is unfortunate but a limitation of CloudControl. I've tried to avoid making the Terraform provider know too much about the internals of CloudControl (which could change and then break the driver's behaviour). For what it's worth, you tend to run into this with several of the major cloud providers.

Normally Terraform infers dependencies between resources by the use of expressions that feed properties of one resource into another, but you can also set up explicit dependencies which will cause the 2 resources in question to be created serially rather than in parallel.

The trick is to make one network domain depend on the other using the explicit `depends_on` property (this works for all resources in Terraform):

```hcl
resource “ddcloud_networkdomain” “domain1” {
  # ...
}

resource “ddcloud_networkdomain” “domain2” {
  # ...

  depends_on = [ "ddcloud_networkdomain.domain1" ]
}
```

If you have more items that `domain2` needs to depend on just put their names inside the `depends_on` array (similar syntax to JavaScript).

**Comment by mingsheng36** [comment]
Alright, great. Will note this down.
