### ISSUE TITLE
Error occur while creating vip node and vm concurrently

### ISSUE THREAD

**Issue by denibenji89** [DimensionDataResearch/terraform-provider-ddcloud#75]
I've encounter errors in several instances while creating a plan with vip. As vip deployment takes precedent over server deployment, thus when assigning node to vip pool, it result in an error as the server to act as a node.
Benjamin Chan

**Comment by tintoy** [comment]
Hi @denibenji89 - would you mind posting the configuration you're using (minus anything sensitive)? I'd like to replicate your issue as closely as possible.

Also, can you tell me what version of Terraform (`terraform -version`) and the CloudControl provider (`terraform-provider-ddcloud --version`) you're using?

**Comment by tintoy** [comment]
Oh, and could you post the error message you're seeing?

**Comment by tintoy** [comment]
BTW, Terraform tries to create as many resources in parallel as it can, subject to dependencies between those resources (e.g. it will never create server before network domain because server references network domain's `id` property in its `networkdomain` property, thereby establishing a dependency).

If your `ddcloud_vip_node` doesn't reference any properties of your `ddcloud_server`,  then Terraform doesn't know there's a dependency there and so will try to create them in parallel (which would cause it to fail, _but only sometimes_). In that case you can use the `depends_on` property on the `ddcloud_vip_node` resource to force it to be created after the `ddcloud_server`.

If that sounds like it might fix your problem, then the [Terraform documentation](https://www.terraform.io/docs/configuration/resources.html#depends_on) has more information on how to do this.

**Comment by tintoy** [comment]
Oh, and if you want more information about resource dependencies, have a look here:

https://www.terraform.io/intro/getting-started/dependencies.html

**Comment by denibenji89** [comment]
[ben.zip](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/files/638475/ben.zip)
![error](https://cloud.githubusercontent.com/assets/23732050/20998408/908caed2-bd48-11e6-8e86-fa883424a3e5.PNG)

**Comment by denibenji89** [comment]
Hey Adam, I've attached the configuration file and error message. Your suggestion should be right as I'm missing the "depend_on" for vip pool member.

**Comment by denibenji89** [comment]
I'm working on the version 1.2 . I like to apologize that I did not read up much prior to posting such issues.

**Comment by tintoy** [comment]
Not a problem - happy to help :)

BTW, the other error (`RESOURCE_BUSY`) is something I'd like to fix before v1.2 goes out. Thanks for reporting this!

**Comment by tintoy** [comment]
FYI - the `RESOURCE_BUSY` error has been fixed for beta 2 (not out yet).

**Comment by tintoy** [comment]
Verified in `v1.3.2` (sorry for the delay in getting back to you).
