### ISSUE TITLE
Hook into cloud-init for ddcloud_server

### ISSUE THREAD

**Issue by liger1978** [DimensionDataResearch/terraform-provider-ddcloud#98]
Hi

Is there a way to hook into `cloud-init` when defining a `ddcloud_server`?  You can do this when using plumbery instead of Terraform to interact with DD Cloud.

If not, can it be added?

Thanks!

**Comment by tintoy** [comment]
Hi - MCP2 does not directly support cloud-init, but we do have a DHCP / iPXE solution which can accomplish this (https://github.com/DimensionDataResearch/mcp2-dhcp-server).

**Comment by tintoy** [comment]
BTW would you mind posting a link to the Plumbery fitting you're referring to?

**Comment by liger1978** [comment]
> BTW would you mind posting a link to the Plumbery fitting you're referring to?

http://plumbery.readthedocs.io/en/latest/fittings.cloud-config.html

**Comment by tintoy** [comment]
I'm asking the folks who built Plumbery to confirm but I'm guessing that the cloud-config is applied _after_ the server is deployed? For stuff like CoreOS and RancherOS, it has to be done at boot time (we can do this using iPXE)

**Comment by liger1978** [comment]
> I'm guessing that the cloud-config is applied after the server is deployed?

It is, and it is a bit clunky.  The client running the plumbery commands seems to require ssh access to the node. Still, better than nothing.

What is the standard/recommended way to add basic config to new nodes on DD cloud?  I looked at the iPXE page you linked, but it seemed a bit convoluted.  I also have no interest in learning ansible currently, as we use Puppet for config mgmnt.  I basically want to know how to bootstrap (CentOS) nodes so that they install a Puppet agent and register with a master. Thanks!

**Comment by tintoy** [comment]
Yeah looking at the code, Plumbery has to already be able to connect to the target server in order to call cloud-init (so you can't use it to install initial SSH keys via cloud-config). But mcp2-dhcp-server will probably do what you want (CloudControl has no direct support for cloud-init but the iPXE boot process allows us to inject arbitrary cloud-config).

**Comment by tintoy** [comment]
Unfortunately, iPXE is as good as it gets at this stage (MCP / CloudControl doesn't support much in the way of boot-time hooks). It's actually not that complicated once you have it set up (and is actually pretty flexible). We use it to deploy RancherOS, Rancher, etc for hosting our internal microservices.

The other option you could probably do is build a custom image that does what you want during boot (but IMHO that's probably _more_ convoluted and less flexible).

**Comment by liger1978** [comment]
Fair enough, thanks for the definitive answer.

**Comment by tintoy** [comment]
BTW, one advantage of mcp2-dhcp-server is that the servers get most of their config from what you've already specified in CloudControl (e.g. IP addresses, iPXE profile from tags) rather having to enter the same information twice.

(sorry I can't offer more than that - it's a platform limitation, although it's one the CloudControl folks could address someday)

**Comment by tintoy** [comment]
Oh, and Ansible was just to install the DHCP server; you could install it by hand or build an equivalent puppet config I imagine. It's not a complex install.

**Comment by jeffstoner** [comment]
You can *probably* use cloud-init with the platform as-is but it would be a bit clunky. The theory (because I have not tested this) is to create a new vm (using an external system) then generate an ISO with your user-data and meta-data, attach it to a server, then export it as an OVF. You can import that as a Customer Image and deploy from it.
During deploy, the server will boot with the ISO attached and cloud-init should do it's could-inity thing.

Caveats:
* Servers are booted during deployment to verify IP information during Guest OS Customization. This may impact your cloud-init sequence of events
* If you import as NGOC, you will have full control over the customization process of the server but "With great power comes great responsibility" - Uncle Ben.

Again, this is off the top of my head, I have not tested this. It may fail. The world could end. Blackholes everywhere!

**Comment by tintoy** [comment]
Heh, yeah - TBH this is why I built that iPXE service :-D

**Comment by tintoy** [comment]
@liger1978 - I'm going to close this issue, but feel free to reopen it if you have any further questions :)
